### ISSUE TITLE
Chest Generation

### ISSUE THREAD

**Issue by chaseyrt** [McJty/LostCities#268] opened 2020-03-14 02:40 UTC
When playing with a small mod-pack, the chests that generate on the 3x3 area (pedestal?) and the ones that spawn in the cornered hallway show up as invisible and when clicked have nothing in them. Those are the only ones ive noticed so far.

**Comment by josephcsible** [comment] 2020-03-14 03:32
Duplicate of #155

**Closed as completed by josephcsible** 2020-03-14 03:32 UTC
