### ISSUE TITLE
Derpy water towers in "ancient" profile

### ISSUE THREAD

**Issue by Seth0067** [McJty/LostCities#26] opened 2017-07-02 00:40 UTC
In "ancient" world type, only the water tower muffin tops spawn:

[pic](http://imgur.com/a/rEE2e)

**Comment by McJty** [comment] 2017-07-02 03:04
Actually the problem is that the ruin generator doesn't start high enough and the water tower is too high. In any case I fixed this already and will be in next release

**Closed by McJty** 2017-07-02 03:04 UTC
