### ISSUE TITLE
city generation doesnt stay in its world

### ISSUE THREAD

**Issue by Tommy7026** [McJty/LostCities#534] opened 2023-02-22 04:57 UTC
i got a weird one here, im on 1.19.2 and have noticed that city generation doesnt seem to be linked to the world but is instead a global change, basically i got a world tuned for rare tall city and a generated a world (only city) to take some pics in for someone and the setting for it got applied to my main rare city world, im unsure if thats a bug or bad code or intentional

**Comment by McJty** [comment] 2023-02-22 05:25
Sorry but I don't understand what you mean. What's the problem and how exactly did you reproduce it?

**Comment by Tommy7026** [comment] 2023-02-22 05:49
> Sorry but I don't understand what you mean. What's the problem and how exactly did you reproduce it?

generate a world with the rare cites preset, fly around a bit, generate a only cites world, fly around that then go to the rare cites and generate new chunks and you should see it

**Comment by Mattabase** [comment] 2023-03-05 03:52
Yeah confirmed, that if select only cities and then load another world with that had another cities setting it will be overridden by whatever city type you selected for the last world you created in the new chunks, so city type selections seems to bleed between saves. 
![image](https://user-images.githubusercontent.com/2126947/222940669-e8b2df3e-f6a3-45d8-9ce7-9149ac8bdacf.png)
The example image was made with the rare cities setting, I then left the world, made a new world with only cities, I then left that world and returned to the rate cities world which now in new chunk gen seems to use the city settings from the last world loaded.

**Comment by Mattabase** [comment] 2024-05-04 04:57
Not sure if this is still an issue for 1.20.1 I will test later this evening, but it still seems to be an issue in 1.19.2 on the latest version.

**Comment by McJty** [comment] 2024-05-04 05:22
I'm busy fixing something that might help with this right at this very moment. For 1.18.2 it's already fixed. So perhaps wait a bit with testing until the new version is released

**Comment by McJty** [comment] 2024-05-14 03:47
Should be fixed now actually. Forgot to close this

**Closed as completed by McJty** 2024-05-14 03:47 UTC
