### ISSUE TITLE
Replacing chests with any other chest BUG

### ISSUE THREAD

**Issue by resinate** [McJty/LostCities#118] opened 2018-04-04 03:46 UTC
when u replace the chest with ANY other chest they spawn in world as invisible/empty

to replacate it: inside library.json replace
      {
        "char": "C",
        "block": "minecraft:chest",
        "loot": "chestloot"
      },

with 

      {
        "char": "C",
        "block": "ironchest:BlockIronChest@6",
        "loot": "chestloot"
      },

also you may have to change conditions and remove the lost cities chest loot for world to generate

**Comment by McJty** [comment] 2018-04-04 03:48
'BlockIronChest' doesn't look valid. It should be all lowercase. Are you sure that's the right registry name?

**Comment by resinate** [comment] 2018-04-04 04:55
yep the chests when appear game some times but empty otherwise everything is invisble but u can still open the chests lol. do u have discord so we can pm little better i can show u all these issues im having LOL

the mod is fking godlike lol just has few issues lol

also not only do chests appear invisible-openable but spawners all change to pigs or become invisible as well lol

**Comment by McJty** [comment] 2018-04-04 05:46
https://discord.gg/knAXM4G

**Comment by josephcsible** [comment] 2018-04-05 23:41
Even on 1.12.2 with the right registry name this happens. I think the problem is that it's not getting its TileEntity in time.

**Comment by josephcsible** [comment] 2018-04-06 03:08
While investigating this, I discovered a crash bug when Iron Chests contain loot tables from any source. I submitted progwml6/ironchest#133 to fix it. Until it's merged, no matter what we do here, you won't be able to use Iron Chests for loot.

**Comment by josephcsible** [comment] 2018-08-25 17:17
Now that that's merged, I re-tested with Lost Cities 2.0.10, Iron Chests 7.0.46.831, and Forge 2678, and it seems to work fine now. Can you confirm?

**Closed as completed** 2018-09-08 17:42 UTC
Labels: bug, needs response from reporter
