### ISSUE TITLE
Incompatibility with JustEnoughIDs

### ISSUE THREAD

**Issue by Bulldog83** [McJty/LostCities#146] opened 2018-07-06 06:34 UTC
Reference to JEID github:
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/4

**Comment by McJty** [comment] 2018-07-06 06:48
Hmm Lost Cities does already support Not Enough IDs mod. I wasn't even aware that JustEnoughIDs existed...

**Comment by Bulldog83** [comment] 2018-07-06 09:01
Not Not Enough IDs, this enother, new mod: [Just Enough ID's](https://minecraft.curseforge.com/projects/jeid)

**Comment by Bulldog83** [comment] 2018-07-06 09:05
This is a new mod. It appeared about three weeks ago.

**Comment by McJty** [comment] 2018-07-06 09:12
Hmm. Any reasons why it exists given that another alternative already exists? It is a bit hard for me to have to support more then one of these mods to be honest

**Comment by Bulldog83** [comment] 2018-07-06 11:16
It implements ID system from minecraft 1.13 rather than simply expanding the range of id like it does NEID.

**Comment by brisingraerowing** [comment] 2018-07-15 18:41
JEID also increases the Biome ID Limit. It is compatible with NEID (you can use both), and will only increase biome IDs when used that way.

**Comment by ubergeek77** [comment] 2018-10-06 22:18
I can confirm that this is unfortunately still an issue with the latest versions of both mods (LostCities 1.12-2.0.12 and JustEnoughIDs 1.0.2-16). While NEIDs and JEIDs more or less accomplish the same goal, I find JEID to be much cleaner in implementation, in addition to being able to remove mods without causing a world management nightmare. In addition, due to personal experience, I find NEIDs to be very buggy and incompatible with both other mods and changes in Forge, and I've never had such problems with JEIDs. It "just works."

I really wish Lost Cities supported JEIDs, it seems to be much more popular these days and is being picked up as the go-to mod for the problems it solves. I would like to use both simultaneously if I can.

**Comment by Seth0067** [comment] 2018-11-08 19:09
Just so people know, this is what you get:

![2018-11-08_11 06 57](https://user-images.githubusercontent.com/22122348/48221291-8d249180-e346-11e8-94ac-c6812a355e83.png)

**Comment by josephcsible** [comment] 2018-11-08 19:14
The problem is that we're writing to the internal private fields of the chunk primer, which don't have the same meaning with Just Enough IDs. We should use the vanilla methods for writing to the primer, and accept the tiny performance hit, and then this will be fixed.

**Comment by Alphanos** [comment] 2019-02-03 03:25
> 
> 
> The problem is that we're writing to the internal private fields of the chunk primer, which don't have the same meaning with Just Enough IDs. We should use the vanilla methods for writing to the primer, and accept the tiny performance hit, and then this will be fixed.

Just curious from your comment about a potential solution.  I couldn't tell from what you wrote if this would be an easy change to make, or if it would be difficult to make that kind of change.  Trying to make the call on JEIDs vs NEIDs for a 1.12 pack, but Lost Cities compatibility is a priority for me =).

**Comment by josephcsible** [comment] 2019-02-03 04:02
The change is easy to make, but last I talked to @McJty about it, he didn't want it to be made, as the new way won't be as fast as it is now.

**Comment by McJty** [comment] 2019-02-03 04:42
The performance hit will not be light and Lost City worldgen is already slow compared to normal. But maybe we should allow for a dual system where the optimized version is still available by default but use the normal api in case either JEID or NEID is in the pack

**Comment by Alphanos** [comment] 2019-02-03 05:18
From my understanding, I think the bug only occurs with JEIDs?  Lots of packs use NEIDs and don't seem to encounter this.

Depending on the difficulty of the workaround, it would be nice to either switch over to it with JEIDs present, or instead offer a config option if that's easier.  JEIDs does have some benefits over NEIDs that it would be nice to be able to take advantage of if possible (more resilience to mod changes, expanded biome/potion/enchantment ID ranges, etc).

For what it's worth, in my pack I plan to include pre-configured chunk pregeneration, which would alleviate most of the performance concerns.  I recognize that not every pack would do that though.

**Comment by McJty** [comment] 2019-02-03 05:55
The bug doesn't occur with NEID because we already special-cased that one

**Comment by josephcsible** [comment] 2019-02-03 05:57
Are you sure? I know [we do in RFTools Dimensions](https://github.com/McJtyMods/RFToolsDimensions/blob/4503dec63cceeb2a6afae62eac0ff31acb36eb9d/src/main/java/mcjty/rftoolsdim/dimensions/world/ChunkPrimerHelper.java), but I don't see any such code in this mod.

**Comment by McJty** [comment] 2019-02-03 06:02
Ah then why is it working with NEID then?

**Comment by McJty** [comment] 2019-02-03 06:03
Anyway, I think I have a plan on how to tackle this. I'm going to implement two modes. One which just use the normal API and one with my optimisation

**Comment by McJty** [comment] 2019-02-04 05:28
I implemented a solution for this that will probably work. Has to be tested well though. I'll keep you posted

**Comment by Alphanos** [comment] 2019-02-04 06:09
Thank you very much!

**Comment by McJty** [comment] 2019-02-12 18:04
Fixed now

**Closed as completed by McJty** 2019-02-12 18:04 UTC
